# Generated by Django 5.0.14 on 2026-01-07 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miepi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrito',
            name='iglesia',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='inscrito',
            name='pastor',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='nombre',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='inscrito',
            name='periodo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
